### ISSUE TITLE
Support exports

### ISSUE THREAD

**Issue by alecmev** [fossamagna/gas-entry-generator#163]
I'm using TypeScript, and currently I have to write something like this for each function I wish to expose:

```ts
declare global {
  namespace NodeJS {
    interface Global {
      foo: any;
    }
  }
}

global.foo = () => "bar";
```

Would be nice if I could just write this instead, which is shorter and a bit more idiomatic:

```ts
export const foo = () => "bar";
```

I think this could be achieved by simply looking for `exports.*` assignments, and wrapping the code that's emitted by Webpack in a loop that iterates over the exports and does `global.x = exports.x` for each.

What do you think?

**Comment by fossamagna** [comment]
@alecmev Thank you for your proposal. Your proposal is fine with me.

I think adding the following options is a good idea. 
```js
var fs = require('fs');
var gasEntryGenerator = require('gas-entry-generator');

var fooSource = fs.readFileSync('foo.js', {encoding: 'utf8'});
var options = {
  comment: true,
  autoGlobalExport: true, // autoGlobalExport is new option! default value is `false`, because of backward compatibility.
};
var entryFunction = gasEntryGenerator(fooSource, options);
console.log(entryFunction);
```

**Comment by alecmev** [comment]
Thanks for adding this! Finally got a chance to test it. When I enable the new option with `["*.ts"]`, I get the following error:

```
ERROR in chunk main [entry]
dist.js
ignored /trimmed/node_modules/seedrandom crypto
Cannot read property 'split' of undefined
```

I'm using `seedrandom` in my project. I've got only one file, `main.ts`, which imports `seedrandom` and exports several functions. Can you, please, look into this? Can provide a full repro later if you're unable to get this error. I'm using this through `gas-webpack-plugin`, just in case.

**Comment by fossamagna** [comment]
@alecmev Thank you for your trying. I tried to reproduce the issue but couldn't. I would appreciate it if you could provide reproducible code.

**Comment by alecmev** [comment]
No problem, here: https://github.com/alecmev/gas-webpack-plugin-repro :slightly_smiling_face: `npm i` and `npx webpack`.

**Comment by fossamagna** [comment]
@alecmev  Thank you. I try it.

> No problem, here: https://github.com/alecmev/gas-webpack-plugin-repro 🙂 `npm i` and `npx webpack`.

**Comment by fossamagna** [comment]
@alecmev 
I was able to reproduce the same error in your repository.And I found the cause.
This is because gas-webpack-plugin was verifying that the paths of modules that are ignored by webpack, such as `crypto`, are subject to auto exports. Modules that are ignored by webpack should be excluded as they cannot get the resource path.
I will address this issue in the near future.
Thank you.

**Comment by fossamagna** [comment]
@alecmev I published gas-webpack-plugin new version.
I fixed issue when using seedrandom.
https://www.npmjs.com/package/gas-webpack-plugin/v/1.2.1

**Comment by alecmev** [comment]
Won't be able to test any time soon, unfortunately, but thank you!
