### ISSUE TITLE
The error is occurring while trying to parse the ES6 syntax

### ISSUE THREAD

**Issue by fossamagna** [fossamagna/gas-entry-generator#184]
The error is occurring while trying to parse the ES6 syntax. It looks like you need to fix the [gas-entry-generator](https://github.com/fossamagna/gas-entry-generator).

_Originally posted by @fossamagna in https://github.com/fossamagna/gas-webpack-plugin/issues/460#issuecomment-733390526_

**Comment by labnol** [comment]
Thank you!
